kind: Deployment
apiVersion: apps/v1
metadata:
   name: myspringbootapp
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: myspringbootapp

   template:
      metadata:
        labels:
          app: myspringbootapp
    
      spec:
       containers:
        - name: myspringbootapp
  
          image: rtekoh/counter-application:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 9099

